/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Profile */
        get: operations["get_my_profile_api_v1_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Goal */
        get: operations["get_goal_api_v1_goals_get"];
        put?: never;
        /** Set Goal */
        post: operations["set_goal_api_v1_goals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/foods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Foods */
        get: operations["search_foods_api_v1_foods_get"];
        put?: never;
        /** Create Food */
        post: operations["create_food_api_v1_foods_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/foods/estimate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Estimate Food */
        post: operations["estimate_food_api_v1_foods_estimate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Meals */
        get: operations["list_meals_api_v1_meals_get"];
        put?: never;
        /** Create Meal */
        post: operations["create_meal_api_v1_meals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meals/analyze-photo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Meal Photo */
        post: operations["analyze_meal_photo_api_v1_meals_analyze_photo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meals/{meal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Meal */
        delete: operations["delete_meal_api_v1_meals__meal_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nutrition/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Daily Nutrition */
        get: operations["get_daily_nutrition_api_v1_nutrition_daily_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Exercises */
        get: operations["search_exercises_api_v1_exercises_get"];
        put?: never;
        /** Create Exercise */
        post: operations["create_exercise_api_v1_exercises_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exercises/estimate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Estimate Exercise */
        post: operations["estimate_exercise_api_v1_exercises_estimate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workouts */
        get: operations["list_workouts_api_v1_workouts_get"];
        put?: never;
        /** Create Workout */
        post: operations["create_workout_api_v1_workouts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workouts/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Workout */
        delete: operations["delete_workout_api_v1_workouts__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/body-metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Body Metrics */
        get: operations["list_body_metrics_api_v1_body_metrics_get"];
        put?: never;
        /** Create Body Metric */
        post: operations["create_body_metric_api_v1_body_metrics_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/body-metrics/{metric_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Body Metric */
        delete: operations["delete_body_metric_api_v1_body_metrics__metric_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard */
        get: operations["get_dashboard_api_v1_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user-memory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List User Memory */
        get: operations["list_user_memory_api_v1_user_memory_get"];
        put?: never;
        /** Set User Memory */
        post: operations["set_user_memory_api_v1_user_memory_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user-memory/{memory_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete User Memory */
        delete: operations["delete_user_memory_api_v1_user_memory__memory_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_api_v1_ai_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/voice-chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Voice Chat */
        post: operations["voice_chat_api_v1_ai_voice_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/weekly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Weekly Summary */
        get: operations["get_weekly_summary_api_v1_analytics_weekly_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/weekly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Weekly Report */
        get: operations["get_weekly_report_api_v1_reports_weekly_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BodyMetric */
        BodyMetric: {
            /** Id */
            id: string;
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            /** Metric Type */
            metric_type: string;
            /** Value */
            value: number;
            /** Unit */
            unit: string;
        };
        /** BodyMetricCreate */
        BodyMetricCreate: {
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            /** Metric Type */
            metric_type: string;
            /** Value */
            value: number;
            /** Unit */
            unit: string;
        };
        /** Body_analyze_meal_photo_api_v1_meals_analyze_photo_post */
        Body_analyze_meal_photo_api_v1_meals_analyze_photo_post: {
            /**
             * Photo
             * Format: binary
             */
            photo: string;
        };
        /** Body_voice_chat_api_v1_ai_voice_chat_post */
        Body_voice_chat_api_v1_ai_voice_chat_post: {
            /**
             * Audio
             * Format: binary
             */
            audio: string;
            /**
             * History
             * @default []
             */
            history: string;
        };
        /** ChatMessage */
        ChatMessage: {
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Content */
            content: string;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Messages */
            messages: components["schemas"]["ChatMessage"][];
        };
        /** ChatResponse */
        ChatResponse: {
            /** Message */
            message: string;
            /** Tools Called */
            tools_called: string[];
        };
        /** DailyNutrition */
        DailyNutrition: {
            /** Date */
            date: string;
            totals: components["schemas"]["NutritionTotals"];
            /** Meal Count */
            meal_count: number;
            remaining: components["schemas"]["MacroRemaining"];
        };
        /** DashboardResponse */
        DashboardResponse: {
            profile: components["schemas"]["UserProfile"];
            nutrition: components["schemas"]["DailyNutrition"];
            /** Today Meals */
            today_meals: components["schemas"]["Meal"][];
            /** Workout Completed Today */
            workout_completed_today: boolean;
            recent_weight: components["schemas"]["BodyMetric"] | null;
            weekly_summary: components["schemas"]["WeeklySummary"];
        };
        /** Exercise */
        Exercise: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Category
             * @enum {string}
             */
            category: "strength" | "cardio" | "mobility" | "other";
        };
        /** ExerciseCreate */
        ExerciseCreate: {
            /** Name */
            name: string;
            /**
             * Category
             * @enum {string}
             */
            category: "strength" | "cardio" | "mobility" | "other";
        };
        /** ExerciseEstimateRequest */
        ExerciseEstimateRequest: {
            /** Name */
            name: string;
        };
        /** Food */
        Food: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Source
             * @enum {string}
             */
            source: "verified" | "user_created" | "ai_estimated";
            /** Default Serving Id */
            default_serving_id: string | null;
            /** Food Servings */
            food_servings?: components["schemas"]["FoodServing"][];
        };
        /** FoodCreate */
        FoodCreate: {
            /** Name */
            name: string;
            /** Servings */
            servings: components["schemas"]["FoodServingCreate"][];
        };
        /** FoodEstimateRequest */
        FoodEstimateRequest: {
            /** Name */
            name: string;
        };
        /** FoodServing */
        FoodServing: {
            /** Id */
            id: string;
            /** Food Id */
            food_id: string;
            /** Serving Description */
            serving_description: string;
            /** Calories */
            calories: number;
            /** Protein G */
            protein_g: number;
            /** Carbs G */
            carbs_g: number;
            /** Fat G */
            fat_g: number;
            /** Fiber G */
            fiber_g: number;
        };
        /** FoodServingCreate */
        FoodServingCreate: {
            /** Serving Description */
            serving_description: string;
            /** Calories */
            calories: number;
            /**
             * Protein G
             * @default 0
             */
            protein_g: number;
            /**
             * Carbs G
             * @default 0
             */
            carbs_g: number;
            /**
             * Fat G
             * @default 0
             */
            fat_g: number;
            /**
             * Fiber G
             * @default 0
             */
            fiber_g: number;
        };
        /** Goal */
        Goal: {
            /** Id */
            id: string;
            /** Calorie Target */
            calorie_target: number | null;
            /** Protein Target G */
            protein_target_g: number | null;
            /** Carb Target G */
            carb_target_g: number | null;
            /** Fat Target G */
            fat_target_g: number | null;
            /** Weight Goal Kg */
            weight_goal_kg: number | null;
            /** Active */
            active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** GoalCreate */
        GoalCreate: {
            /** Calorie Target */
            calorie_target?: number | null;
            /** Protein Target G */
            protein_target_g?: number | null;
            /** Carb Target G */
            carb_target_g?: number | null;
            /** Fat Target G */
            fat_target_g?: number | null;
            /** Weight Goal Kg */
            weight_goal_kg?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MacroRemaining */
        MacroRemaining: {
            /** Calorie Target */
            calorie_target: number | null;
            /** Protein Target G */
            protein_target_g: number | null;
            /** Carb Target G */
            carb_target_g: number | null;
            /** Fat Target G */
            fat_target_g: number | null;
            /** Calories Remaining */
            calories_remaining: number | null;
            /** Protein Remaining G */
            protein_remaining_g: number | null;
            /** Carbs Remaining G */
            carbs_remaining_g: number | null;
            /** Fat Remaining G */
            fat_remaining_g: number | null;
        };
        /** Meal */
        Meal: {
            /** Id */
            id: string;
            /** User Id */
            user_id: string;
            /**
             * Logged At
             * Format: date-time
             */
            logged_at: string;
            /**
             * Meal Type
             * @enum {string}
             */
            meal_type: "breakfast" | "lunch" | "dinner" | "snack";
            /**
             * Input Source
             * @enum {string}
             */
            input_source: "text" | "photo" | "manual";
            /** Raw Input */
            raw_input: string | null;
            /** Meal Items */
            meal_items?: components["schemas"]["MealItem"][];
        };
        /** MealCreate */
        MealCreate: {
            /**
             * Logged At
             * Format: date-time
             */
            logged_at: string;
            /**
             * Meal Type
             * @enum {string}
             */
            meal_type: "breakfast" | "lunch" | "dinner" | "snack";
            /** Items */
            items: components["schemas"]["MealItemCreate"][];
            /**
             * Input Source
             * @default manual
             * @enum {string}
             */
            input_source: "manual" | "text" | "photo";
        };
        /** MealItem */
        MealItem: {
            /** Id */
            id: string;
            /** Food Id */
            food_id: string;
            /** Serving Id */
            serving_id: string;
            /** Quantity */
            quantity: number;
            /**
             * Nutrition Confidence
             * @enum {string}
             */
            nutrition_confidence: "verified" | "estimated";
            /** Calories */
            calories: number;
            /** Protein G */
            protein_g: number;
            /** Carbs G */
            carbs_g: number;
            /** Fat G */
            fat_g: number;
            /** Fiber G */
            fiber_g: number;
            /** Food Name */
            food_name?: string | null;
            /** Serving Description */
            serving_description?: string | null;
        };
        /** MealItemCreate */
        MealItemCreate: {
            /** Food Id */
            food_id: string;
            /** Serving Id */
            serving_id: string;
            /** Quantity */
            quantity: number;
        };
        /** NutritionTotals */
        NutritionTotals: {
            /** Calories */
            calories: number;
            /** Protein G */
            protein_g: number;
            /** Carbs G */
            carbs_g: number;
            /** Fat G */
            fat_g: number;
            /** Fiber G */
            fiber_g: number;
        };
        /** PhotoAnalysisItem */
        PhotoAnalysisItem: {
            /** Food Name */
            food_name: string;
            /** Quantity */
            quantity: number;
            resolved: components["schemas"]["ResolvedFood"] | null;
        };
        /** PhotoAnalysisResponse */
        PhotoAnalysisResponse: {
            /** Items */
            items: components["schemas"]["PhotoAnalysisItem"][];
        };
        /** ResolvedFood */
        ResolvedFood: {
            /** Food Id */
            food_id: string;
            /** Serving Id */
            serving_id: string;
            /** Food Name */
            food_name: string;
            /** Serving Description */
            serving_description: string;
        };
        /** UserMemoryCreate */
        UserMemoryCreate: {
            /**
             * Category
             * @enum {string}
             */
            category: "goal" | "equipment" | "preference" | "constraint" | "observation";
            /** Key */
            key: string;
            /** Value */
            value: string;
        };
        /** UserMemoryEntry */
        UserMemoryEntry: {
            /** Id */
            id: string;
            /**
             * Category
             * @enum {string}
             */
            category: "goal" | "equipment" | "preference" | "constraint" | "observation";
            /** Key */
            key: string;
            /** Value */
            value: string;
        };
        /** UserProfile */
        UserProfile: {
            /** Id */
            id: string;
            /** Display Name */
            display_name: string | null;
            /** Timezone */
            timezone: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VoiceChatResponse */
        VoiceChatResponse: {
            /** Transcript */
            transcript: string;
            /** Message */
            message: string;
            /** Tools Called */
            tools_called: string[];
            /** Audio Base64 */
            audio_base64: string;
        };
        /** WeeklyReport */
        WeeklyReport: {
            summary: components["schemas"]["WeeklySummary"];
            /** Narrative */
            narrative: string;
        };
        /** WeeklySummary */
        WeeklySummary: {
            /** Period Days */
            period_days: number;
            /** Days Logged */
            days_logged: number;
            /** Avg Calories */
            avg_calories: number | null;
            /** Avg Protein G */
            avg_protein_g: number | null;
            /** Avg Carbs G */
            avg_carbs_g: number | null;
            /** Avg Fat G */
            avg_fat_g: number | null;
            /** Calorie Adherence Rate */
            calorie_adherence_rate: number | null;
            /** Workout Count */
            workout_count: number;
            /** Workout Total Volume Kg */
            workout_total_volume_kg: number;
            /** Meal Logging Streak */
            meal_logging_streak: number;
            /** Workout Logging Streak */
            workout_logging_streak: number;
            /** Weight Start */
            weight_start: number | null;
            /** Weight End */
            weight_end: number | null;
            /** Weight Change */
            weight_change: number | null;
        };
        /** WorkoutExercise */
        WorkoutExercise: {
            /** Id */
            id: string;
            /** Exercise Id */
            exercise_id: string;
            /** Order Index */
            order_index: number;
            /** Exercise Name */
            exercise_name?: string | null;
            /** Workout Sets */
            workout_sets?: components["schemas"]["WorkoutSet"][];
            /**
             * Volume Kg
             * @default 0
             */
            volume_kg: number;
        };
        /** WorkoutExerciseCreate */
        WorkoutExerciseCreate: {
            /** Exercise Id */
            exercise_id: string;
            /** Sets */
            sets: components["schemas"]["WorkoutSetCreate"][];
        };
        /** WorkoutSession */
        WorkoutSession: {
            /** Id */
            id: string;
            /** User Id */
            user_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Ended At */
            ended_at: string | null;
            /** Notes */
            notes: string | null;
            /** Workout Exercises */
            workout_exercises?: components["schemas"]["WorkoutExercise"][];
            /**
             * Total Volume Kg
             * @default 0
             */
            total_volume_kg: number;
        };
        /** WorkoutSessionCreate */
        WorkoutSessionCreate: {
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Ended At */
            ended_at?: string | null;
            /** Notes */
            notes?: string | null;
            /** Exercises */
            exercises: components["schemas"]["WorkoutExerciseCreate"][];
        };
        /** WorkoutSet */
        WorkoutSet: {
            /** Id */
            id: string;
            /** Set Number */
            set_number: number;
            /** Reps */
            reps: number | null;
            /** Weight Kg */
            weight_kg: number | null;
            /** Duration Seconds */
            duration_seconds: number | null;
        };
        /** WorkoutSetCreate */
        WorkoutSetCreate: {
            /** Reps */
            reps?: number | null;
            /** Weight Kg */
            weight_kg?: number | null;
            /** Duration Seconds */
            duration_seconds?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_my_profile_api_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
        };
    };
    get_goal_api_v1_goals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Goal"] | null;
                };
            };
        };
    };
    set_goal_api_v1_goals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Goal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_foods_api_v1_foods_get: {
        parameters: {
            query?: {
                query?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Food"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_food_api_v1_foods_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FoodCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Food"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    estimate_food_api_v1_foods_estimate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FoodEstimateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Food"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_meals_api_v1_meals_get: {
        parameters: {
            query?: {
                for_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meal"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_meal_api_v1_meals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MealCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_meal_photo_api_v1_meals_analyze_photo_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_analyze_meal_photo_api_v1_meals_analyze_photo_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoAnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_meal_api_v1_meals__meal_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_daily_nutrition_api_v1_nutrition_daily_get: {
        parameters: {
            query?: {
                for_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyNutrition"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_exercises_api_v1_exercises_get: {
        parameters: {
            query?: {
                query?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exercise"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_exercise_api_v1_exercises_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exercise"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    estimate_exercise_api_v1_exercises_estimate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseEstimateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exercise"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_workouts_api_v1_workouts_get: {
        parameters: {
            query?: {
                for_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutSession"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_workout_api_v1_workouts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkoutSessionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutSession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_workout_api_v1_workouts__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_body_metrics_api_v1_body_metrics_get: {
        parameters: {
            query?: {
                metric_type?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BodyMetric"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_body_metric_api_v1_body_metrics_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BodyMetricCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BodyMetric"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_body_metric_api_v1_body_metrics__metric_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                metric_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_api_v1_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
        };
    };
    list_user_memory_api_v1_user_memory_get: {
        parameters: {
            query?: {
                category?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMemoryEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_user_memory_api_v1_user_memory_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserMemoryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMemoryEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_memory_api_v1_user_memory__memory_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memory_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_api_v1_ai_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    voice_chat_api_v1_ai_voice_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_voice_chat_api_v1_ai_voice_chat_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoiceChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_weekly_summary_api_v1_analytics_weekly_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklySummary"];
                };
            };
        };
    };
    get_weekly_report_api_v1_reports_weekly_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklyReport"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
