import type { components } from "./api";

export type UserProfile = components["schemas"]["UserProfile"];
export type Food = components["schemas"]["Food"];
export type FoodServing = components["schemas"]["FoodServing"];
export type FoodCreate = components["schemas"]["FoodCreate"];
export type FoodServingCreate = components["schemas"]["FoodServingCreate"];
export type Meal = components["schemas"]["Meal"];
export type MealItem = components["schemas"]["MealItem"];
export type MealCreate = components["schemas"]["MealCreate"];
export type MealItemCreate = components["schemas"]["MealItemCreate"];
export type DailyNutrition = components["schemas"]["DailyNutrition"];
export type NutritionTotals = components["schemas"]["NutritionTotals"];
export type MacroRemaining = components["schemas"]["MacroRemaining"];
export type Exercise = components["schemas"]["Exercise"];
export type ExerciseCreate = components["schemas"]["ExerciseCreate"];
export type WorkoutSession = components["schemas"]["WorkoutSession"];
export type WorkoutExercise = components["schemas"]["WorkoutExercise"];
export type WorkoutSet = components["schemas"]["WorkoutSet"];
export type WorkoutSessionCreate = components["schemas"]["WorkoutSessionCreate"];
export type WorkoutExerciseCreate = components["schemas"]["WorkoutExerciseCreate"];
export type WorkoutSetCreate = components["schemas"]["WorkoutSetCreate"];
export type BodyMetric = components["schemas"]["BodyMetric"];
export type BodyMetricCreate = components["schemas"]["BodyMetricCreate"];
